version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: blog_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qrc135zx
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: >
      sh -c "python wait_for_db.py && python main.py"
    volumes:
      - .:/app
    ports:
      - "4000:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:qrc135zx@db:5432/blog_app_db

volumes:
  postgres_data: